# Generated by Django 5.2.5 on 2026-01-20 12:54

import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """"данный класс описывает миграцию в базу данных"""

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAssignmentSubmissions',
            fields=[
                ('submission_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID набора прикрепленных файлов')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('practical_assignment_id', models.BigIntegerField(verbose_name='ID задания')),
                ('practical_assignment_name', models.CharField(max_length=255, verbose_name='Название задания')),
                ('lecture_name', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('attempt_number', models.IntegerField(verbose_name='Номер попытки')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('file_count', models.IntegerField(verbose_name='Количество файлов')),
                ('total_size', models.BigIntegerField(verbose_name='Общий размер')),
            ],
            options={
                'verbose_name': 'Сданная практическая работа',
                'verbose_name_plural': 'Сданные практические работы',
                'db_table': 'view_assignment_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCourseLectures',
            fields=[
                ('course_id', models.BigIntegerField(verbose_name='ID курса')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('lecture_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID лекции')),
                ('lecture_name', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('lecture_content', models.TextField(verbose_name='Содержание лекции')),
                ('lecture_document_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к документу')),
                ('lecture_order', models.IntegerField(verbose_name='Порядок лекции')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Лекция курса',
                'verbose_name_plural': 'Лекции курсов',
                'db_table': 'view_course_lectures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCoursePracticalAssignments',
            fields=[
                ('course_id', models.BigIntegerField(verbose_name='ID курса')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('lecture_id', models.BigIntegerField(verbose_name='ID лекции')),
                ('lecture_name', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('lecture_order', models.IntegerField(verbose_name='Порядок лекции')),
                ('practical_assignment_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID задания')),
                ('practical_assignment_name', models.CharField(max_length=255, verbose_name='Название задания')),
                ('practical_assignment_description', models.TextField(verbose_name='Описание задания')),
                ('assignment_document_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к документу')),
                ('assignment_criteria', models.TextField(blank=True, null=True, verbose_name='Критерии оценки')),
                ('assignment_deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('grading_type', models.CharField(max_length=20, verbose_name='Тип оценки')),
                ('max_score', models.IntegerField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Практическая работа курса',
                'verbose_name_plural': 'Практические работы курсов',
                'db_table': 'view_course_practical_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCourseTests',
            fields=[
                ('course_id', models.BigIntegerField(verbose_name='ID курса')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('lecture_id', models.BigIntegerField(verbose_name='ID лекции')),
                ('lecture_name', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('lecture_order', models.IntegerField(verbose_name='Порядок лекции')),
                ('test_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID теста')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('test_description', models.TextField(blank=True, null=True, verbose_name='Описание теста')),
                ('is_final', models.BooleanField(verbose_name='Финальный тест')),
                ('max_attempts', models.IntegerField(blank=True, null=True, verbose_name='Максимум попыток')),
                ('grading_form', models.CharField(max_length=20, verbose_name='Форма оценки')),
                ('passing_score', models.IntegerField(blank=True, null=True, verbose_name='Проходной балл')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тест курса',
                'verbose_name_plural': 'Тесты курсов',
                'db_table': 'view_course_tests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type_name', models.CharField(help_text='Название типа ответа (2-50 символов)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа'), django.core.validators.MaxLengthValidator(50, message='Максимум 50 символов'), django.core.validators.RegexValidator(message='Разрешены только буквы, пробелы, дефисы и подчёркивания', regex='^[а-яА-Яa-zA-Z_\\- ]+$')], verbose_name='Название типа ответа')),
                ('answer_type_description', models.TextField(blank=True, help_text='Описание типа ответа (до 500 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(500, message='Описание не должно превышать 1000 символов')], verbose_name='Описание типа ответа')),
            ],
            options={
                'verbose_name': 'Тип ответа',
                'verbose_name_plural': 'Типы ответов',
                'db_table': 'answer_type',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_name', models.CharField(help_text='Название типа курса (2-100 символов)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов'), django.core.validators.RegexValidator(message='Разрешены только буквы, цифры, пробелы, дефисы и подчёркивания', regex='^[а-яА-Яa-zA-Z0-9_\\- ]+$')], verbose_name='Название типа курса')),
                ('course_type_description', models.TextField(blank=True, help_text='Необязательное поле. Описание типа курса (до 250 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(250, message='Описание не должно превышать 250 символов')], verbose_name='Описание типа курса')),
            ],
            options={
                'verbose_name': 'Тип курса',
                'verbose_name_plural': 'Типы курсов',
                'db_table': 'course_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Имя должно содержать минимум 2 символа'), django.core.validators.MaxLengthValidator(50, message='Имя должно содержать максимум 50 символов'), django.core.validators.RegexValidator(code='invalid_first_name', message='Имя может содержать только буквы, дефисы и пробелы!', regex='^[а-яА-Яa-zA-Z\\- ]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, message='Фамилия должна содержать минимум 1 символ'), django.core.validators.MaxLengthValidator(50, message='Фамилия должна содержать максимум 50 символов'), django.core.validators.RegexValidator(code='invalid_last_name', message='Фамилия может содержать только буквы, дефисы и пробелы!', regex='^[а-яА-Яa-zA-Z\\- ]+$')], verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Введите корректную почту: она должна содержать точку, доменное имя, название адреса и символ @'), django.core.validators.MaxLengthValidator(254, message='Почта может содержать максимум 254 символа')], verbose_name='Почта')),
                ('username', models.CharField(help_text='Обязательное поле. Не более 150 символов. Только буквы, цифры и символы: @ . - _', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='Имя пользователя должно содержать минимум 1 символ'), django.core.validators.MaxLengthValidator(150, message='Имя пользователя должно содержать максимум 150 символов'), django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя может содержать только буквы, цифры и символы: @ . - _', regex='^[\\w.@-]+$')], verbose_name='Имя пользователя')),
                ('patronymic', models.CharField(blank=True, help_text='Необязательное поле. Если указано, должно быть от 2 до 50 символов', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Отчество должно содержать минимум 2 символа'), django.core.validators.MaxLengthValidator(50, message='Отчество должно содержать максимум 50 символов'), django.core.validators.RegexValidator(code='invalid_patronymic', message='Отчество может содержать только буквы, дефисы и пробелы', regex='^[а-яА-Яa-zA-Z\\- ]*$')], verbose_name='Отчество')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('profile_theme', models.CharField(blank=True, help_text='Необязательное поле. Название цветовой темы интерфейса', max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30, message='Название темы должно содержать максимум 30 символов'), django.core.validators.RegexValidator(code='invalid_theme', message='Тема может содержать только латинские буквы, цифры, пробелы, дефисы и подчёркивания!', regex='^[a-zA-Z0-9_\\- ]*$')], verbose_name='Цветовая тема')),
                ('position', models.CharField(blank=True, help_text='Полное название должности на текущем месте работы требуется для методистов и преподавателей', max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100, message='Название должности должно содержать максимум 100 символов')], verbose_name='Должность')),
                ('educational_institution', models.CharField(blank=True, help_text='Указание места работы или места получения образования (например, название ВУЗа или колледжа) требуется для методистов и преподавателей!', max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100, message='Название учебного заведения должно содержать максимум 100 символов')], verbose_name='Учебное заведение')),
                ('certificate_file', models.FileField(blank=True, help_text='Подтверждение места работы или уровня образования. Максимальный размер: 10 МБ', null=True, upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'], message='Поддерживаемые форматы: JPG, JPEG, PNG, PDF, DOC, DOCX')], verbose_name='Справка с места работы/документ об образовании')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_status_name', models.CharField(help_text='Название статуса задания (2-50 символов)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа'), django.core.validators.MaxLengthValidator(50, message='Максимум 50 символов'), django.core.validators.RegexValidator(message='Разрешены только буквы, пробелы, дефисы и подчёркивания', regex='^[а-яА-Яa-zA-Z_\\- ]+$')], verbose_name='Название статуса задания')),
            ],
            options={
                'verbose_name': 'Статус задания',
                'verbose_name_plural': 'Статусы заданий',
                'db_table': 'assignment_status',
                'constraints': [models.CheckConstraint(condition=models.Q(('assignment_status_name__regex', '^[а-яА-Яa-zA-Z_\\- ]+$')), name='assignment_status_valid_chars')],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category_name', models.CharField(error_messages={'required': 'Это обязательное поле', 'unique': 'Категория с таким названием уже существует'}, help_text='Название категории курса (2-100 символов)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов'), django.core.validators.RegexValidator(message='Разрешены только буквы, цифры, пробелы, дефисы и подчёркивания', regex='^[а-яА-Яa-zA-Z0-9_\\- ]+$')], verbose_name='Название категории курса')),
            ],
            options={
                'verbose_name': 'Категория курса',
                'verbose_name_plural': 'Категории курсов',
                'db_table': 'course_category',
                'constraints': [models.CheckConstraint(condition=models.Q(('course_category_name__regex', '^[а-яА-Яa-zA-Z0-9_\\- ]+$')), name='course_category_name_valid_chars'), models.CheckConstraint(condition=models.Q(('course_category_name__regex', '^\\s*$'), _negated=True), name='course_category_not_only_spaces')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Название курса (3-200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа'), django.core.validators.MaxLengthValidator(200, message='Максимум 200 символов'), django.core.validators.RegexValidator(message='Недопустимые символы в названии курса', regex='^[а-яА-Яa-zA-Z0-9_\\- ,.!?"\\\'():; ]+$')], verbose_name='Название курса')),
                ('course_description', models.TextField(blank=True, help_text='Необязательное поле. Описание курса (до 300 символов, необязательно)', null=True, validators=[django.core.validators.MaxLengthValidator(300, message='Описание не должно превышать 300 символов')], verbose_name='Описание курса')),
                ('course_price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена курса в рублях (если курс является платным)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной'), django.core.validators.MaxValueValidator(9999999.99, message='Цена курса слишком велика, такого быть не может!')], verbose_name='Цена курса')),
                ('course_photo_path', models.ImageField(blank=True, help_text='Изображение курса (необязательно)', null=True, upload_to='course_photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Поддерживаются только изображения форматов .jpg, .jpeg и .png')], verbose_name='Фотография курса')),
                ('has_certificate', models.BooleanField(default=False, help_text='Определяет, выдаётся ли сертификат после завершения курса', verbose_name='Есть сертификат')),
                ('course_max_places', models.IntegerField(blank=True, help_text='Максимальное количество участников (необязательно)', null=True, validators=[django.core.validators.MinValueValidator(1, message='Количество мест должно быть положительным'), django.core.validators.MaxValueValidator(1000, message='Максимум 1000 мест')], verbose_name='Максимум мест')),
                ('course_hours', models.IntegerField(help_text='Общая продолжительность курса в часах (от 1 до 3000)', validators=[django.core.validators.MinValueValidator(1, message='Курс должен длиться минимум 1 час'), django.core.validators.MaxValueValidator(3000, message='Слишком большое количество часов')], verbose_name='Количество часов')),
                ('is_completed', models.BooleanField(default=True, help_text='Завершено ли наполнение курса материалами', verbose_name='Завершён')),
                ('code_link', models.CharField(blank=True, help_text='Ссылка для доступа к комнате видео-встречи курса, например ранее созданный Яндекс.Телемост (необязательно)', max_length=200, null=True, validators=[django.core.validators.URLValidator(message='Пожалуйста, введите корректную ссылку!')], verbose_name='Ccылка видео-встречи курса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('course_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unireax_main.coursecategory', verbose_name='Категория курса')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.coursetype', verbose_name='Тип курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(help_text='Название лекции (3-200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа'), django.core.validators.MaxLengthValidator(200, message='Максимум 200 символов')], verbose_name='Название лекции')),
                ('lecture_content', models.TextField(help_text='Текст лекции (50-50000 символов)', validators=[django.core.validators.MinLengthValidator(50, message='Содержание должно содержать минимум 50 символов'), django.core.validators.MaxLengthValidator(50000, message='Содержание не должно превышать 50000 символов')], verbose_name='Содержание лекции')),
                ('lecture_document_path', models.FileField(blank=True, help_text='Дополнительный документ к лекции (необязательно)', null=True, upload_to='lectures/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt'], message='Поддерживаются файлы: PDF, DOC, DOCX, PPT, PPTX, TXT')], verbose_name='Документ лекции')),
                ('lecture_order', models.IntegerField(help_text='Порядковый номер лекции в курсе', validators=[django.core.validators.MinValueValidator(1, message='Порядок должен быть положительным числом')], verbose_name='Порядок лекции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность лекции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'db_table': 'lecture',
                'ordering': ['course', 'lecture_order'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-значный код с почты для восстановления пароля', max_length=6, validators=[django.core.validators.MinLengthValidator(6, message='Код должен содержать 6 символов!'), django.core.validators.MaxLengthValidator(6, message='Код должен содержать 6 символов!'), django.core.validators.RegexValidator(message='Код должен содержать только цифры', regex='^[0-9]+$')], verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код восстановления пароля',
                'verbose_name_plural': 'Коды восстановления пароля',
                'db_table': 'password_reset_code',
            },
        ),
        migrations.CreateModel(
            name='PracticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_assignment_name', models.CharField(help_text='Название практического задания (3-200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа'), django.core.validators.MaxLengthValidator(200, message='Максимум 200 символов')], verbose_name='Название задания')),
                ('practical_assignment_description', models.TextField(help_text='Подробное описание задания (20-5000 символов)', validators=[django.core.validators.MinLengthValidator(20, message='Описание должно содержать минимум 20 символов'), django.core.validators.MaxLengthValidator(5000, message='Описание не должно превышать 5000 символов')], verbose_name='Описание задания')),
                ('assignment_document_path', models.FileField(blank=True, help_text='Файл с дополнительными материалами (необязательно)', null=True, upload_to='assignments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip', 'rar'], message='Поддерживаются файлы: PDF, DOC, DOCX, ZIP, RAR')], verbose_name='Документ задания')),
                ('assignment_criteria', models.TextField(blank=True, help_text='Критерии оценки задания (до 2000 символов, необязательно)', null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Критерии не должны превышать 2000 символов')], verbose_name='Критерии оценки')),
                ('assignment_deadline', models.DateTimeField(blank=True, help_text='Крайний срок сдачи задания (необязательно)', null=True, verbose_name='Срок сдачи')),
                ('grading_type', models.CharField(choices=[('points', 'По баллам'), ('pass_fail', 'Зачёт/незачёт')], default='points', max_length=20, verbose_name='Тип оценки')),
                ('max_score', models.IntegerField(blank=True, help_text='Максимально возможный балл за задание', null=True, validators=[django.core.validators.MinValueValidator(1, message='Максимальный балл должен быть положительным'), django.core.validators.MaxValueValidator(1000, message='Максимальный балл не должен превышать 1000')], verbose_name='Максимальный балл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность практического задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_can_pin_after_deadline', models.BooleanField(verbose_name='Можно ли прикреплять работу после срока сдачи')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.lecture', verbose_name='Лекция')),
            ],
            options={
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
                'db_table': 'practical_assignment',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Текст вопроса (5-2000 символов)', validators=[django.core.validators.MinLengthValidator(5, message='Текст вопроса должен содержать минимум 5 символов'), django.core.validators.MaxLengthValidator(2000, message='Текст вопроса не должен превышать 2000 символов')], verbose_name='Текст вопроса')),
                ('question_score', models.IntegerField(default=1, help_text='Количество баллов за правильный ответ', validators=[django.core.validators.MinValueValidator(0, message='Балл за вопрос не может быть отрицательным'), django.core.validators.MaxValueValidator(100, message='Балл за вопрос не должен превышать 100')], verbose_name='Балл за вопрос')),
                ('correct_text', models.TextField(blank=True, help_text='Правильный ответ для вопросов с текстовым ответом (до 2000 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Текст ответа не должен превышать 2000 символов')], verbose_name='Правильный ответ')),
                ('question_order', models.IntegerField(help_text='Порядковый номер вопроса в тесте', validators=[django.core.validators.MinValueValidator(1, message='Порядок вопроса должен быть положительным')], verbose_name='Порядок вопроса')),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.answertype', verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField(help_text='Текст слева для сопоставления (1-500 символов)', validators=[django.core.validators.MinLengthValidator(1, message='Текст не может быть пустым!'), django.core.validators.MaxLengthValidator(500, message='Текст не должен превышать 500 символов!')], verbose_name='Левый текст')),
                ('right_text', models.TextField(help_text='Текст справа для сопоставления (1-500 символов)', validators=[django.core.validators.MinLengthValidator(1, message='Текст не может быть пустым!'), django.core.validators.MaxLengthValidator(500, message='Текст не должен превышать 500 символов!')], verbose_name='Правый текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Пара соответствия',
                'verbose_name_plural': 'Пары соответствия',
                'db_table': 'matching_pair',
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(help_text='Текст варианта ответа (1-1000 символов)', validators=[django.core.validators.MinLengthValidator(1, message='Текст варианта не может быть пустым'), django.core.validators.MaxLengthValidator(1000, message='Текст варианта не должен превышать 1000 символов')], verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(help_text='Является ли этот вариант правильным ответом', verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'choice_option',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Оценка курса от 1 до 5 звёзд', verbose_name='Рейтинг')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('comment_review', models.TextField(blank=True, help_text='Дополнительный комментарий (до 2000 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Комментарий не должен превышать 2000 символов')], verbose_name='Комментарий к отзыву')),
                ('is_approved', models.BooleanField(default=False, help_text='Проверен ли отзыв модератором', verbose_name='Одобрен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(error_messages={'max_length': 'Максимум 40 символов!', 'required': 'Это обязательное для заполнения поле', 'unique': 'Роль с таким названием уже существует!'}, help_text='От 3 до 40 символов. Буквы, пробелы, дефисы (-), подчеркивания (_)', max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Роль должна содержать минимум 3 символа'), django.core.validators.RegexValidator(code='invalid_chars', message='Разрешены только буквы, пробелы, дефисы (-) и подчеркивания (_)', regex='^[а-яА-Яa-zA-Z_\\- ]+$')], verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
                'constraints': [models.CheckConstraint(condition=models.Q(('role_name__regex', '^.{3,40}$')), name='role_length_check'), models.CheckConstraint(condition=models.Q(('role_name__regex', '^[а-яА-Яa-zA-Z_\\- ]+$')), name='role_valid_chars'), models.CheckConstraint(condition=models.Q(('role_name__regex', '^\\s*$'), _negated=True), name='role_not_only_spaces')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Роль пользователя в системе', null=True, on_delete=django.db.models.deletion.SET_NULL, to='unireax_main.role', verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='TeacherAssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Путь к файлу', max_length=500, verbose_name='Путь к файлу')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_type', models.CharField(choices=[('example', 'Пример выполнения работы'), ('material', 'Дополнительный материал'), ('correction', 'Исправление'), ('template', 'Шаблон'), ('other', 'Другое')], default='material', max_length=20, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('practical_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_files', to='unireax_main.practicalassignment', verbose_name='Практическое задание')),
                ('uploaded_by', models.ForeignKey(limit_choices_to=models.Q(('role__role_name__in', ['преподаватель', 'методист'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл преподавателя к заданию',
                'verbose_name_plural': 'Файлы преподавателей к заданиям',
                'db_table': 'teacher_assignment_file',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Название теста (3-200 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа'), django.core.validators.MaxLengthValidator(200, message='Максимум 200 символов')], verbose_name='Название теста')),
                ('test_description', models.TextField(blank=True, help_text='Описание теста (до 2000 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Описание не должно превышать 2000 символов')], verbose_name='Описание теста')),
                ('is_final', models.BooleanField(default=False, help_text='Является ли тест финальным для курса', verbose_name='Финальный тест')),
                ('max_attempts', models.IntegerField(blank=True, help_text='Максимальное количество попыток прохождения теста', null=True, validators=[django.core.validators.MinValueValidator(1, message='Количество попыток должно быть положительным'), django.core.validators.MaxValueValidator(100, message='Максимум 100 попыток')], verbose_name='Максимум попыток')),
                ('grading_form', models.CharField(choices=[('points', 'По баллам'), ('pass_fail', 'Зачёт/незачёт')], default='points', max_length=20, verbose_name='Форма оценки')),
                ('passing_score', models.IntegerField(blank=True, help_text='Минимальный балл для успешного прохождения теста', null=True, validators=[django.core.validators.MinValueValidator(0, message='Проходной балл не может быть отрицательным'), django.core.validators.MaxValueValidator(3000, message='Проходной балл не должен превышать 3000')], verbose_name='Проходной балл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность теста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.lecture', verbose_name='Лекция')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'test',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения')),
                ('final_score', models.IntegerField(blank=True, help_text='Общий набранный балл за тест', null=True, validators=[django.core.validators.MinValueValidator(0, message='Итоговый балл не может быть отрицательным'), django.core.validators.MaxValueValidator(10000, message='Итоговый балл не должен превышать 10000')], verbose_name='Итоговый балл')),
                ('is_passed', models.BooleanField(blank=True, help_text='Зачтён ли тест', null=True, verbose_name='Зачтено')),
                ('attempt_number', models.IntegerField(default=1, help_text='Номер попытки прохождения теста', validators=[django.core.validators.MinValueValidator(1, message='Номер попытки должен быть положительным')], verbose_name='Номер попытки')),
                ('time_spent', models.IntegerField(blank=True, help_text='Время, затраченное на выполнение теста в секундах', null=True, validators=[django.core.validators.MinValueValidator(0, message='Время не может быть отрицательным'), django.core.validators.MaxValueValidator(86400, message='Время не должно превышать 24 часа')], verbose_name='Время выполнения (секунды)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'db_table': 'test_result',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Текстовый ответ пользователя (до 2000 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Текст ответа не должен превышать 2000 символов')], verbose_name='Текст ответа')),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ответа')),
                ('attempt_number', models.IntegerField(default=1, help_text='Номер попытки прохождения теста', validators=[django.core.validators.MinValueValidator(1, message='Номер попытки должен быть положительным')], verbose_name='Номер попытки')),
                ('score', models.IntegerField(blank=True, help_text='Набранный балл за ответ', null=True, validators=[django.core.validators.MinValueValidator(0, message='Балл не может быть отрицательным!'), django.core.validators.MaxValueValidator(1000, message='Балл не должен превышать 1000')], verbose_name='Балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, help_text='Дата записи пользователя на курс', verbose_name='Дата регистрации')),
                ('status_course', models.BooleanField(default=False, help_text='Завершил ли пользователь курс', verbose_name='Курс завершён')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Дата и время оплаты курса (если требуется)', null=True, verbose_name='Дата оплаты')),
                ('completion_date', models.DateField(blank=True, help_text='Дата фактического завершения курса', null=True, verbose_name='Дата завершения')),
                ('course_price', models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая цена, по которой был приобретён курс', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной')], verbose_name='Цена курса')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли участие пользователя в курсе', verbose_name='Активность слушателя на курсе')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь на курсе',
                'verbose_name_plural': 'Пользователи на курсах',
                'db_table': 'user_course',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Уникальный номер сертификата (5-50 символов)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Номер сертификата должен содержать минимум 5 символов'), django.core.validators.MaxLengthValidator(50, message='Номер сертификата не должен превышать 50 символов'), django.core.validators.RegexValidator(message='Номер сертификата может содержать только заглавные латинские буквы, цифры, дефисы и подчёркивания', regex='^[A-Z0-9\\-_]+$')], verbose_name='Номер сертификата')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Дата выдачи сертификата', verbose_name='Дата выдачи')),
                ('certificate_file_path', models.CharField(blank=True, help_text='Путь к файлу сертификата (до 500 символов)', max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500, message='Путь к файлу не должен превышать 500 символов')], verbose_name='Путь к файлу сертификата')),
                ('user_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.usercourse', verbose_name='Пользователь на курсе')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='UserMatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_selected_right_text', models.TextField(help_text='Текст, выбранный пользователем для сопоставления (1-500 символов)', validators=[django.core.validators.MinLengthValidator(1, message='Выбранный текст не может быть пустым'), django.core.validators.MaxLengthValidator(500, message='Выбранный текст не должен превышать 500 символов')], verbose_name='Выбранный правый текст')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('matching_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.matchingpair', verbose_name='Пара соответствия')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.useranswer', verbose_name='Ответ пользователя')),
            ],
            options={
                'verbose_name': 'Ответ на сопоставление',
                'verbose_name_plural': 'Ответы на сопоставления',
                'db_table': 'user_matching_answer',
            },
        ),
        migrations.CreateModel(
            name='UserPracticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, help_text='Дата и время отправки работы', null=True, verbose_name='Дата сдачи')),
                ('attempt_number', models.IntegerField(default=1, help_text='Номер попытки сдачи задания', validators=[django.core.validators.MinValueValidator(1, message='Номер попытки должен быть положительным')], verbose_name='Номер попытки')),
                ('comment', models.TextField(blank=True, help_text='Комментарий студента к отправленной работе (до 2000 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(2000, message='Комментарий не должен превышать 2000 символов')], verbose_name='Комментарий к сдаче')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('practical_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.practicalassignment', verbose_name='Практическое задание')),
                ('submission_status', models.ForeignKey(help_text='Текущий статус выполнения задания', on_delete=django.db.models.deletion.PROTECT, to='unireax_main.assignmentstatus', verbose_name='Статус сдачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сдача практического задания',
                'verbose_name_plural': 'Сдачи практических заданий',
                'db_table': 'user_practical_assignment',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, help_text='Количество набранных баллов', null=True, validators=[django.core.validators.MinValueValidator(0, message='Балл не может быть отрицательным'), django.core.validators.MaxValueValidator(1000, message='Балл не должен превышать 1000')], verbose_name='Балл')),
                ('is_passed', models.BooleanField(blank=True, help_text='Зачтена ли работа', null=True, verbose_name='Зачтено')),
                ('comment_feedback', models.TextField(blank=True, help_text='Комментарий преподавателя к работе (до 5000 символов)', null=True, validators=[django.core.validators.MaxLengthValidator(5000, message='Комментарий не должен превышать 5000 символов')], verbose_name='Комментарий преподавателя')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('given_by', models.ForeignKey(blank=True, help_text='Преподаватель, который проверил работу', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оценку выставил')),
                ('user_practical_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.userpracticalassignment', verbose_name='Сдача задания')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл с выполненным заданием', upload_to='assignment_submissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'md', 'rtf', 'odt', 'ods', 'odp', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'ico', 'tiff', 'tif', 'bmp', 'ai', 'eps', 'mp3', 'wav', 'ogg', 'aac', 'flac', 'mp4', 'avi', 'mov', 'webm', 'mkv', 'wmv', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'py', 'java', 'cpp', 'c', 'h', 'hpp', 'cs', 'dart', 'html', 'css', 'js', 'ts', 'php', 'rb', 'go', 'swift', 'kt', 'rs', 'sql', 'json', 'xml', 'yaml', 'yml', 'toml', 'epub', 'mobi', 'azw', 'dwg', 'dxf', 'stl', 'obj', 'fbx', 'gltf', 'glb', 'blend'])], verbose_name='Файл сдачи')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_name', models.CharField(help_text='Оригинальное имя файла', max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(help_text='Размер файла в байтах', validators=[django.core.validators.MinValueValidator(0, message='Размер файла не может быть отрицательным!'), django.core.validators.MaxValueValidator(104857600, message='Размер файла не должен превышать 100 МБ!')], verbose_name='Размер файла')),
                ('description', models.CharField(blank=True, help_text='Краткое описание содержимого файла (до 500 символов)', max_length=500, null=True, verbose_name='Описание файла')),
                ('user_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.userpracticalassignment', verbose_name='Сдача задания')),
            ],
            options={
                'verbose_name': 'Файл сдачи задания',
                'verbose_name_plural': 'Файлы сдачи заданий',
                'db_table': 'assignment_submission_file',
            },
        ),
        migrations.CreateModel(
            name='UserSelectedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('choice_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.choiceoption', verbose_name='Выбранный вариант')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.useranswer', verbose_name='Ответ пользователя')),
            ],
            options={
                'verbose_name': 'Выбранный вариант',
                'verbose_name_plural': 'Выбранные варианты',
                'db_table': 'user_selected_choice',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала работы на курсе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность преподавателя/методиста на курсе')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Персонал курса',
                'verbose_name_plural': 'Персоналы курсов',
                'db_table': 'course_teacher',
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 1, 20)), _connector='OR'), name='course_teacher_start_date_future_check')],
                'unique_together': {('course', 'teacher')},
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('course_price__isnull', True), ('course_price__gte', 0), _connector='OR'), name='course_price_non_negative_check'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('course_max_places__isnull', True), ('course_max_places__gt', 0), _connector='OR'), name='course_max_places_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('course_hours__gt', 0)), name='course_hours_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_order__gt', 0)), name='lecture_order_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('course', 'lecture_order'), name='unique_lecture_order_course'),
        ),
        migrations.AddConstraint(
            model_name='passwordresetcode',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9]{6}$')), name='password_reset_code_format_check'),
        ),
        migrations.AddConstraint(
            model_name='practicalassignment',
            constraint=models.CheckConstraint(condition=models.Q(('grading_type__in', ['points', 'pass_fail'])), name='grading_type_check'),
        ),
        migrations.AddConstraint(
            model_name='practicalassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grading_type', 'points'), _negated=True), models.Q(('max_score__isnull', False), ('max_score__gt', 0)), _connector='OR'), name='max_score_required_for_points_check'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range_check'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course', 'user')},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__regex', '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')), name='user_email_format'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('username__regex', '^[\\w.@-]+$')), name='user_username_format'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__regex', '^[а-яА-Яa-zA-Z\\- ]+$')), name='user_first_name_format'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_name__regex', '^[а-яА-Яa-zA-Z\\- ]+$')), name='user_last_name_format'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignmentfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_type__in', ['example', 'material', 'correction', 'template', 'other'])), name='teacher_file_type_check'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('grading_form__in', ['points', 'pass_fail'])), name='test_grading_form_check'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__isnull', True), ('max_attempts__gt', 0), _connector='OR'), name='test_max_attempts_check'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('question_score__gte', 0)), name='question_score_check'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('question_order__gt', 0)), name='question_order_check'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test', 'question_order'), name='unique_question_order_test'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='test_result_attempt_number_check'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.CheckConstraint(condition=models.Q(('time_spent__isnull', True), models.Q(('time_spent__gte', 0), ('time_spent__lte', 86400)), _connector='OR'), name='test_result_time_spent_check'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('user', 'test', 'attempt_number')},
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='user_answer_attempt_number_check'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='user_answer_score_check'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'attempt_number')},
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(('registration_date__lte', datetime.date(2026, 1, 20))), name='user_course_registration_date_past_check'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status_course', True), _negated=True), ('completion_date__isnull', False), _connector='OR'), name='user_course_completion_date_required_check'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(('course_price__isnull', True), ('course_price__gte', 0), _connector='OR'), name='user_course_price_non_negative_check'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('certificate_number__regex', '^[A-Z0-9\\-_]+$')), name='certificate_number_format'),
        ),
        migrations.AlterUniqueTogether(
            name='usermatchinganswer',
            unique_together={('user_answer', 'matching_pair')},
        ),
        migrations.AddConstraint(
            model_name='userpracticalassignment',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='user_practical_assignment_attempt_number_check'),
        ),
        migrations.AddConstraint(
            model_name='userpracticalassignment',
            constraint=models.UniqueConstraint(fields=('user', 'practical_assignment', 'attempt_number'), name='unique_user_assignment_attempt'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmissionfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='assignment_file_size_check'),
        ),
        migrations.AlterUniqueTogether(
            name='userselectedchoice',
            unique_together={('user_answer', 'choice_option')},
        ),
    ]
