# Generated by Django 5.2.5 on 2026-01-25 16:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
        migrations.RemoveConstraint(
            model_name='usercourse',
            name='user_course_registration_date_past_check',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_theme',
        ),
        migrations.AddField(
            model_name='user',
            name='is_light_theme',
            field=models.BooleanField(choices=[(True, 'Светлая'), (False, 'Тёмная')], default=True, help_text='Выберите цветовую тему интерфейса', verbose_name='Тема интерфейса'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая цена, по которой был приобретён курс', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной')], verbose_name='Цена курса на момент покупки'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 1, 25)), _connector='OR'), name='course_teacher_start_date_future_check'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(('registration_date__lte', datetime.date(2026, 1, 25))), name='user_course_registration_date_past_check'),
        ),
    ]
