# Generated by Django 5.2.5 on 2026-01-31 22:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0002_remove_courseteacher_course_teacher_start_date_future_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
        migrations.RemoveConstraint(
            model_name='usercourse',
            name='user_course_registration_date_past_check',
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Дата записи пользователя на курс', verbose_name='Дата регистрации'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 1, 31)), _connector='OR'), name='course_teacher_start_date_future_check'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(('registration_date__lte', datetime.date(2026, 1, 31))), name='user_course_registration_date_past_check'),
        ),
    ]
