# Generated by Django 5.2.5 on 2026-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0003_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercourse',
            name='user_course_registration_date_past_check',
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user', 'status_course'], name='user_course_user_id_33d674_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['registration_date'], name='user_course_registr_190d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['completion_date'], name='user_course_complet_da2eb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(('completion_date__isnull', True), ('completion_date__gte', models.F('registration_date')), _connector='OR'), name='user_course_completion_date_check'),
        ),
    ]
