# Generated by Django 5.2.5 on 2026-02-08 21:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0004_remove_usercourse_user_course_registration_date_past_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 2, 8)), _connector='OR'), name='course_teacher_start_date_future_check'),
        ),
    ]
