# Generated by Django 5.2.5 on 2026-02-09 21:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0005_remove_courseteacher_course_teacher_start_date_future_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
        migrations.AddField(
            model_name='practicalassignment',
            name='passing_score',
            field=models.IntegerField(blank=True, help_text='Минимальный балл для зачета задания (только для балльной системы)', null=True, validators=[django.core.validators.MinValueValidator(0, message='Проходной балл не может быть отрицательным')], verbose_name='Проходной балл'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 2, 9)), _connector='OR'), name='course_teacher_start_date_future_check'),
        ),
        migrations.AddConstraint(
            model_name='practicalassignment',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__isnull', True), ('passing_score__gte', 0), _connector='OR'), name='passing_score_non_negative_check'),
        ),
    ]
