# Generated by Django 5.2.5 on 2026-02-15 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0006_remove_courseteacher_course_teacher_start_date_future_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 2, 15)), _connector='OR'), name='course_teacher_start_date_future_check'),
        ),
    ]
