# Generated by Django 5.2.5 on 2026-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0007_remove_courseteacher_course_teacher_start_date_future_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Уникальный ID платежа от платежной системы', max_length=255, null=True, verbose_name='ID платежа в ЮKassa'),
        ),
    ]
