# Generated by Django 5.2.5 on 2026-03-02 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0008_usercourse_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewAssignmentSubmissions',
        ),
        migrations.DeleteModel(
            name='ViewCourseLectures',
        ),
        migrations.DeleteModel(
            name='ViewCoursePracticalAssignments',
        ),
        migrations.DeleteModel(
            name='ViewCourseTests',
        ),
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('start_date__gte', datetime.date(2026, 3, 2)), _connector='OR'), name='course_teacher_start_date_future_check'),
        ),
    ]
