# Generated by Django 5.2.5 on 2026-03-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0009_delete_viewassignmentsubmissions_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseteacher',
            name='course_teacher_start_date_future_check',
        ),
    ]
