# Generated by Django 5.2.5 on 2026-04-03 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0010_remove_courseteacher_course_teacher_start_date_future_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Имя пользователя')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP адрес')),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время попытки')),
                ('success', models.BooleanField(default=False, verbose_name='Успешный вход')),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входа',
                'db_table': 'login_attempts',
                'indexes': [models.Index(fields=['ip_address', 'attempt_time'], name='login_attem_ip_addr_d70b51_idx'), models.Index(fields=['username', 'attempt_time'], name='login_attem_usernam_3815a1_idx')],
            },
        ),
    ]
