# Generated by Django 5.2.5 on 2026-04-13 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0011_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='unireax_main.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный курс',
                'verbose_name_plural': 'Избранные курсы',
                'db_table': 'favorite_course',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='favorite_co_user_id_12abbd_idx'), models.Index(fields=['course'], name='favorite_co_course__ee5693_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
