# Generated by Django 5.2.5 on 2026-04-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0013_alter_loginattempt_options_loginattempt_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Комментарий методиста при отклонении заявки', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to='unireax_main.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__role_name': 'преподаватель'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Заявка преподавателя',
                'verbose_name_plural': 'Заявки преподавателей',
                'db_table': 'teacher_application',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'course')},
            },
        ),
    ]
