# Generated by Django 5.2.5 on 2026-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0014_teacherapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_find_teacher',
            field=models.BooleanField(blank=True, help_text='Отображать курс в каталоге для преподавателей как вакансию', null=True, verbose_name='Ведётся ли поиск преподавателей'),
        ),
    ]
