# Generated by Django 5.2.5 on 2026-04-23 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0015_course_is_find_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_content',
            field=models.TextField(help_text='Текст лекции (50-50000 символов)', validators=[django.core.validators.MinLengthValidator(10, message='Содержание должно содержать минимум 10 символов'), django.core.validators.MaxLengthValidator(50000, message='Содержание не должно превышать 50000 символов')], verbose_name='Содержание лекции'),
        ),
        migrations.CreateModel(
            name='CoursePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('post_type', models.CharField(choices=[('announcement', 'Объявление'), ('question', 'Вопрос'), ('reminder', 'Напоминание')], default='announcement', max_length=20, verbose_name='Тип')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='unireax_main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Пост курса',
                'verbose_name_plural': 'Посты курсов',
                'db_table': 'course_post',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='unireax_main.coursepost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий к посту',
                'verbose_name_plural': 'Комментарии к постам',
                'db_table': 'course_post_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
