# Generated by Django 5.2.5 on 2026-04-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0016_alter_lecture_lecture_content_coursepost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='unireax_main.coursepostcomment', verbose_name='Родительский комментарий'),
        ),
    ]
