# Generated by Django 5.2.5 on 2026-04-28 14:40

import django.db.models.deletion
from django.db import migrations, models


def create_application_statuses(apps, schema_editor):
    """Создает записи статусов в справочнике"""
    ApplicationStatus = apps.get_model('unireax_main', 'ApplicationStatus')
    
    statuses = [
        {'code': 'pending', 'name': 'На рассмотрении'},
        {'code': 'approved', 'name': 'Одобрена'},
        {'code': 'rejected', 'name': 'Отклонена'},
    ]
    for status in statuses:
        ApplicationStatus.objects.get_or_create(code=status['code'], defaults=status)


def create_post_types(apps, schema_editor):
    """Создает записи типов постов в справочнике"""
    PostType = apps.get_model('unireax_main', 'PostType')
    
    types = [
        {'code': 'announcement', 'name': 'Объявление'},
        {'code': 'question', 'name': 'Вопрос'},
        {'code': 'reminder', 'name': 'Напоминание'},
    ]
    for post_type in types:
        PostType.objects.get_or_create(code=post_type['code'], defaults=post_type)


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0017_coursepostcomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'application_status',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип поста',
                'verbose_name_plural': 'Типы постов',
                'db_table': 'post_type',
            },
        ),
        
        migrations.RunPython(create_application_statuses),
        migrations.RunPython(create_post_types),
        
        migrations.AddField(
            model_name='teacherapplication',
            name='status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='applications',
                to='unireax_main.applicationstatus',
                verbose_name='Статус'
            ),
        ),
        migrations.AddField(
            model_name='coursepost',
            name='post_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='posts',
                to='unireax_main.posttype',
                verbose_name='Тип поста'
            ),
        ),
    ]